name: Codzienny ETL (Aktualizacja Rynku IT)

on:
  schedule:
    - cron: '0 3,15 * * *'
  workflow_dispatch: 

jobs:
  uruchom-rurociag:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Pobranie kodu z repozytorium
        uses: actions/checkout@v3

      - name: 🚀 Pobranie i uruchomienie MinIO (Natywnie)
        run: |
          wget https://dl.min.io/server/minio/release/linux-amd64/minio
          chmod +x minio
          MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=supersecretpassword ./minio server /tmp/minio-data &
          sleep 5

      - name: 🐍 Konfiguracja środowiska Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Instalacja bibliotek
        run: pip install -r requirements.txt

      - name: ⛏️ Ekstrakcja z No Fluff Jobs
        run: python extract_poland.py

      - name: ⛏️ Ekstrakcja z Just Join IT
        run: python extract_jjit.py

      - name: 🔄 Transformacja i ładowanie (No Fluff Jobs)
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: python transform_poland.py

      - name: 🔄 Transformacja i ładowanie (Just Join IT - Append)
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: python transform_jjit.py
