name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch: 

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Odwiedzenie i pełne wybudzenie strony (Ping)
        run: curl -sL https://kamil-rynek-it.streamlit.app > /dev/null || true
