name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Odwiedzenie strony (Ping)
        run: curl -sL https://kamil-rynek-it.streamlit.app > /dev/null